-------------USER_user-------------
--TABLESPACE
CREATE TABLESPACE KAD_TS
        DATAFILE 'KAD_TS'
        SIZE 7M
        AUTOEXTEND ON NEXT 5M
        MAXSIZE 100 M;

--DROP TABLESPACE TASK_WAVE_ADMIN_TS INCLUDING CONTENTS and DATAFILES;

create TEMPORARY TABLESPACE KAD_TS_TEMP
    TEMPFILE 'KAD_TS_TEMP'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 30M;

--DROP TABLESPACE TASK_WAVE_ADMIN_TS_TEMP INCLUDING CONTENTS and DATAFILES;

--PROFILE
    CREATE PROFILE KAD_profile
  LIMIT
    SESSIONS_PER_USER UNLIMITED
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    CONNECT_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    PRIVATE_SGA UNLIMITED
    COMPOSITE_LIMIT UNLIMITED
    FAILED_LOGIN_ATTEMPTS UNLIMITED
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_REUSE_TIME UNLIMITED
    PASSWORD_LOCK_TIME UNLIMITED
    PASSWORD_GRACE_TIME UNLIMITED;

--user
    CREATE USER KAD IDENTIFIED BY 1
    PROFILE KAD_profile
    DEFAULT TABLESPACE KAD_TS
    TEMPORARY TABLESPACE KAD_TS_TEMP
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;

    --DROP USER USER_TASK_WAVE cascade;
--PRIV
    GRANT CREATE SESSION, ALTER SESSION
    TO KAD;
    GRANT RESTRICTED SESSION TO KAD;

    GRANT CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE,
    COMMENT ANY TABLE, SELECT ANY TABLE, INSERT ANY TABLE,
    UPDATE ANY TABLE, DELETE ANY TABLE,
    FLASHBACK ANY TABLE, ALTER ANY INDEX, DROP ANY INDEX,
    CREATE ANY INDEX, CREATE ANY TRIGGER, ALTER ANY TRIGGER,
    DROP ANY TRIGGER, EXECUTE ANY PROCEDURE, CREATE ANY PROCEDURE,
    ALTER ANY PROCEDURE, DROP ANY PROCEDURE, CREATE ANY SEQUENCE,
    ALTER ANY SEQUENCE, DROP ANY SEQUENCE, CREATE ANY VIEW,
    ALTER ANY ANALYTIC VIEW,
    DROP ANY VIEW, CREATE ANY SYNONYM, DROP ANY SYNONYM TO KAD;
    grant EXECUTE ON sys.dbms_crypto to KAD;
    ALTER USER KAD QUOTA UNLIMITED ON KAD_TS;
