--tablespace
CREATE TABLESPACE TS_KAD_Lb3
        DATAFILE 'TS_KAD_Lb3'
        SIZE 7M
        AUTOEXTEND ON NEXT 5M
        MAXSIZE 100 M;

DROP TABLESPACE TS_KAD_Lb3 INCLUDING CONTENTS and DATAFILES;

--profile
CREATE PROFILE PF_KADCORE_Lb3 LIMIT
    FAILED_LOGIN_ATTEMPTS 7
    SESSIONS_PER_USER 3
    PASSWORD_LIFE_TIME 60
    PASSWORD_REUSE_TIME 365
    PASSWORD_LOCK_TIME 1
    CONNECT_TIME 180
    IDLE_TIME 30;

drop profile PF_KADCORE_Lb3;

--user
CREATE USER U1_KAD_PDB IDENTIFIED BY 1
    DEFAULT TABLESPACE TS_KAD_Lb3 quota unlimited on TS_KAD_Lb3
    PROFILE PF_KADCORE_Lb3
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;

GRANT CREATE SESSION TO U1_KAD_PDB;
GRANT
    CREATE TABLE,
    CREATE VIEW,
    DROP ANY TABLE,
    DROP ANY VIEW TO U1_KAD_PDB;


GRANT
    INSERT any table
    to U1_KAD_PDB;

--DROP USER U1_KAD_PDB cascade;
DROP USER C##KAD CASCADE ;